Repository red-hat-storage/ceph-csi, pull requests merged in 2021-12, with the labels that each got.

#49 Sync rhs/ceph-csi:devel with ceph/ceph-csi:devel
  charts/ceph-csi-rbd/templates/csiplugin-configmap.yaml
  cmd/cephcsi.go
  go.mod
  go.sum
  internal/csi-addons/rbd/identity.go
  internal/csi-addons/server/server.go
  internal/csi-addons/server/server_test.go
  internal/rbd/driver.go
  internal/rbd/driver_test.go
  internal/rbd/rbd_journal.go
  internal/rbd/replicationcontrollerserver.go
  internal/util/util.go
  scripts/minikube.sh
  scripts/rook.sh
  vendor/github.com/csi-addons/spec/lib/go/identity/identity.pb.go
  vendor/github.com/csi-addons/spec/lib/go/identity/identity_grpc.pb.go
  vendor/github.com/csi-addons/spec/lib/go/replication/replication.pb.go
  vendor/github.com/csi-addons/spec/lib/go/replication/replication_grpc.pb.go
  vendor/modules.txt
Labels: approved, lgtm

#51 Sync rhs/ceph-csi:devel with ceph/ceph-csi:devel
  internal/rbd/errors.go
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: approved, lgtm

#53 Sync rhs/ceph-csi:devel with ceph/ceph-csi:devel
  .github/workflows/golangci-lint.yaml
  charts/ceph-csi-rbd/values.yaml
  docs/deploy-rbd.md
  e2e/cephfs.go
  e2e/rbd.go
  examples/rbd/storageclass.yaml
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm

#55 Sync rhs/ceph-csi:devel with ceph/ceph-csi:devel
  .mergify.yml
  build.env
  cmd/cephcsi.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/utils.go
  go.mod
  internal/rbd/controllerserver.go
  internal/rbd/driver/driver.go
  internal/rbd/driver/driver_test.go
  internal/rbd/globals.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_healer.go
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
  internal/rbd/replicationcontrollerserver.go
  internal/util/util.go
  vendor/modules.txt
Labels: approved, lgtm

#57 BUG 2030745: rbd: added RBD features support for krbd
  charts/ceph-csi-rbd/values.yaml
  docs/deploy-rbd.md
  examples/rbd/storageclass.yaml
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/invalid-bug

#58 BUG 2030742: rbd: recreate dummy image with new image features and 1MiB size
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm, bugzilla/invalid-bug, bugzilla/severity-medium

#59 BUG 2032417: rbd: repair imageid after resync
  internal/rbd/rbd_journal.go
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#61 BUG 2030742: rbd: reset dummy image id
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#63 Sync rhs/ceph-csi:devel with ceph/ceph-csi:devel
  .commitlintrc.yml
  README.md
  charts/ceph-csi-rbd/templates/nodeplugin-clusterrolebinding.yaml
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  cmd/cephcsi.go
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  docs/deploy-rbd.md
  e2e/ceph_user.go
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/clone.go
  e2e/configmap.go
  e2e/deploy-vault.go
  e2e/e2e_test.go
  e2e/kms.go
  e2e/migration.go
  e2e/namespace.go
  e2e/node.go
  e2e/pod.go
  e2e/pvc.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/resize.go
  e2e/snapshot.go
  e2e/staticpvc.go
  e2e/upgrade-cephfs.go
  e2e/upgrade-rbd.go
  e2e/upgrade.go
  e2e/utils.go
  examples/rbd/pod-block-restore.yaml
  examples/rbd/pvc-block-restore.yaml
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/migration.go
  internal/rbd/mirror.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/snapshot.go
  internal/util/cephcmds.go
  internal/util/cephcmds_test.go
  scripts/Dockerfile.test
Labels: approved, lgtm

#64 BUG 2030752: rbd: execute rbd image promote with timeout
  internal/rbd/mirror.go
  internal/rbd/replicationcontrollerserver.go
  internal/util/cephcmds.go
  internal/util/cephcmds_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent
