Repository red-hat-storage/ceph-csi, pull requests merged in 2022-10, with the labels that each got.

#136 Sync downstream devel with upstream devel
  .github/workflows/stale.yaml
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm

#137 BUG 2132359: rbd: remove dummy image workaround
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/invalid-bug

#138 Sync the upstream changes from `ceph/ceph-csi:devel` into the `devel` branch
  docs/ceph-csi-upgrade.md
  e2e/deployment.go
  e2e/e2e_test.go
  e2e/pvc.go
  e2e/rbd.go
  e2e/utils.go
  internal/cephfs/nodeserver.go
  internal/csi-common/utils.go
  internal/csi-common/utils_test.go
  internal/nfs/nodeserver/nodeserver.go
  internal/rbd/nodeserver.go
  scripts/install-helm.sh
  scripts/minikube.sh
Labels: approved, lgtm

#139 Bug 2132270: util: make inode metrics optional in FilesystemNodeGetVolumeStats()
  internal/cephfs/nodeserver.go
  internal/csi-common/utils.go
  internal/csi-common/utils_test.go
  internal/nfs/nodeserver/nodeserver.go
  internal/rbd/nodeserver.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#142 doc: update owners aliases file
  OWNERS_ALIASES
Labels: approved, lgtm

#141 Bug 2134930: rebase: ParseAcceptLanguage takes a long time to parse complex tags
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/width/tables10.0.0.go
  vendor/golang.org/x/text/width/tables11.0.0.go
  vendor/golang.org/x/text/width/tables12.0.0.go
  vendor/golang.org/x/text/width/tables13.0.0.go
  vendor/golang.org/x/text/width/tables9.0.0.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#144 BUG 2138155: fix namespace name update in metadata and rados object
  e2e/rbd.go
  internal/journal/voljournal.go
  internal/rbd/rbd_journal.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
