Repository red-hat-storage/ceph-csi, pull requests merged in 2022-07, with the labels that each got.

#110 Sync with upstream devel branch
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  e2e/pvc.go
  e2e/rbd.go
  go.mod
  go.sum
  internal/cephfs/core/clone.go
  internal/cephfs/core/clone_test.go
  internal/cephfs/store/fsjournal.go
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
  internal/util/util.go
  vendor/k8s.io/apiserver/pkg/audit/union.go
  vendor/k8s.io/kubernetes/pkg/api/v1/pod/util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm

#111 Bug 2099965: rbd: provide option to disable setting metadata on rbd images
  cmd/cephcsi.go
  internal/controller/controller.go
  internal/controller/persistentvolume/persistentvolume.go
  internal/rbd/controllerserver.go
  internal/rbd/driver/driver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/util/util.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#113 Sync devel branch with upstream
  go.mod
  go.sum
  internal/rbd/errors.go
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
  scripts/rook.sh
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/gracefulswitch.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm

#115 BUG 2110013: rbd: remove checkHealthyPrimary check
  internal/rbd/errors.go
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug
