Repository red-hat-storage/ceph-csi, pull requests merged in 2022-06, with the labels that each got.

#98 Bug 2094856: rbd: create token and use it for vault SA
  charts/ceph-csi-rbd/templates/nodeplugin-clusterrole.yaml
  charts/ceph-csi-rbd/templates/provisioner-clusterrole.yaml
  deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml
  deploy/rbd/kubernetes/csi-provisioner-rbac.yaml
  internal/kms/vault_sa.go
  internal/util/k8s/version.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#101 [DOWNSTREAM ONLY] ci: disable dependabot PR creation for Actions
  .github/dependabot.yml
Labels: approved, lgtm

#103 [DOWNSTEAM-ONLY] Bug 2098562: fix build failure related to VaultTenantSA.createToken
  internal/kms/vault_sa.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#106 BUG 2101660: Fix RBD failover
  internal/rbd/replicationcontrollerserver.go
  internal/rbd/replicationcontrollerserver_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#105 BUG 2101662: rbd: issue resync only if the force flag is set
  internal/rbd/replicationcontrollerserver.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#108 Bug 2099965: track metadata for RBD-images
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  cmd/cephcsi.go
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  docs/deploy-rbd.md
  e2e/deployment.go
  e2e/rbd.go
  e2e/utils.go
  internal/controller/controller.go
  internal/controller/persistentvolume/persistentvolume.go
  internal/rbd/controllerserver.go
  internal/rbd/driver/driver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/util/k8s/parameters.go
  internal/util/util.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
