Repository red-hat-storage/ceph-csi, pull requests merged in 2022-02, with the labels that each got.

#73 Bug 2050056: util: use `vaultNamespace` if `vaultAuthNamespace` is not set
  internal/kms/vault.go
  internal/kms/vault_tokens_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#74 rbd: add AAD(additionalAuthData) while unwrapping the DEK
  internal/kms/keyprotect.go
Labels: approved, lgtm

#77 BUG 2052027: fix omap deletion in DeleteSnapshot
  internal/cephfs/controllerserver.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#78 Sync rhs/ceph:devel with ceph/ceph:devel
  charts/ceph-csi-cephfs/templates/storageclass.yaml
  charts/ceph-csi-rbd/templates/storageclass.yaml
  go.mod
  go.sum
  internal/cephfs/nodeserver.go
  internal/rbd/controllerserver.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/have_field.go
  vendor/k8s.io/kubernetes/pkg/volume/plugins.go
  vendor/modules.txt
Labels: approved, lgtm

#79 Bug 2053156: cephfs: dont set explicit permissions on the volume
  internal/cephfs/nodeserver.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#81 BUG 2059080: rbd update image features
  charts/ceph-csi-rbd/values.yaml
  docs/deploy-rbd.md
  e2e/rbd.go
  e2e/rbd_helper.go
  examples/rbd/storageclass.yaml
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified
