Repository red-hat-storage/ceph-csi, pull requests merged in 2023-11, with the labels that each got.

#204 Syncing latest changes from devel for ceph-csi
  go.mod
  go.sum
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/uuid.go
  vendor/modules.txt
Labels: approved, lgtm

#205 Syncing latest changes from devel for ceph-csi
  go.mod
  go.sum
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/uuid.go
  vendor/modules.txt
Labels: approved, lgtm

#206 Syncing latest changes from devel for ceph-csi
  internal/cephfs/controllerserver.go
  internal/cephfs/core/clone.go
  internal/cephfs/core/snapshot.go
  internal/cephfs/errors/errors.go
  internal/cephfs/store/fsjournal.go
Labels: approved, lgtm

#203 BUG 2246388: fix: Invalid "invalid encryption kms configuration" error
  e2e/rbd.go
  internal/rbd/controllerserver.go
  internal/rbd/encryption.go
  internal/rbd/encryption_test.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_journal.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#208 Syncing latest changes from devel for ceph-csi
  .github/pull_request_template.md
  Makefile
  PendingReleaseNotes.md
  cmd/cephcsi.go
  deploy.sh
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  docs/design/proposals/volume-condition.md
  e2e/node.go
  e2e/rbd.go
  e2e/upgrade-rbd.go
  go.mod
  internal/cephfs/driver.go
  internal/cephfs/nodeserver.go
  internal/csi-common/server.go
  internal/csi-common/utils.go
  internal/health-checker/checker.go
  internal/health-checker/filechecker.go
  internal/health-checker/filechecker_test.go
  internal/health-checker/manager.go
  internal/health-checker/manager_test.go
  internal/health-checker/statchecker.go
  internal/health-checker/statchecker_test.go
  internal/nfs/driver/driver.go
  internal/rbd/driver/driver.go
  internal/rbd/encryption.go
  internal/rbd/nodeserver.go
  internal/util/csiconfig.go
  internal/util/util.go
  scripts/build-multi-arch-image.sh
Labels: approved, lgtm

#207 Syncing latest changes from devel for ceph-csi
  internal/cephfs/controllerserver.go
  internal/cephfs/core/clone.go
  internal/cephfs/core/snapshot.go
  internal/cephfs/errors/errors.go
  internal/cephfs/store/fsjournal.go
Labels: approved, lgtm

#209 Syncing latest changes from devel for ceph-csi
  internal/cephfs/driver.go
  internal/csi-common/server.go
  internal/csi-common/utils.go
Labels: approved, lgtm

#210 Syncing latest changes from devel for ceph-csi
  PendingReleaseNotes.md
  scripts/Dockerfile.devel
Labels: approved, lgtm

#211 Syncing latest changes from devel for ceph-csi
  .github/workflows/tickgit.yaml
  Makefile
  PendingReleaseNotes.md
  api/deploy/ocp/scc.go
  charts/ceph-csi-rbd/values.yaml
  deploy/csi-config-map-sample.yaml
  docs/deploy-rbd.md
  e2e/configmap.go
  e2e/utils.go
  internal/cephfs/core/clone.go
  internal/cephfs/driver.go
  internal/cephfs/fuserecovery.go
  internal/csi-addons/networkfence/fencing.go
  internal/csi-addons/networkfence/fencing_test.go
  internal/rbd/driver/driver.go
  internal/rbd/nodeserver.go
  internal/rbd/nodeserver_test.go
  internal/rbd/rbd_attach.go
  internal/util/crushlocation.go
  internal/util/csiconfig.go
  internal/util/csiconfig_test.go
  internal/util/fscrypt/fscrypt.go
  internal/util/k8s/client.go
  internal/util/k8s/node.go
  internal/util/read_affinity.go
  internal/util/read_affinity_test.go
  internal/util/topology.go
  scripts/Dockerfile.test
Labels: approved, lgtm

#213 Syncing latest changes from devel for ceph-csi
  PendingReleaseNotes.md
  deploy/csi-config-map-sample.yaml
  docs/deploy-cephfs.md
  e2e/cephfs.go
  e2e/nfs.go
  e2e/utils.go
  go.mod
  go.sum
  internal/cephfs/core/metadata.go
  internal/cephfs/core/volume.go
  scripts/rook.sh
  vendor/github.com/aws/aws-sdk-go-v2/aws/config.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/endpoints.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_client.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/endpoints.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/generated.json
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/smithy-go/CHANGELOG.md
  vendor/github.com/aws/smithy-go/go_module_metadata.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/SECURITY.md
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/slogr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/logr/slogr/slogsink.go
  vendor/k8s.io/klog/v2/.golangci.yaml
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
  vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
  vendor/k8s.io/klog/v2/k8s_references_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/modules.txt
Labels: approved, lgtm

#214 BUG 2249600: cephfs: set Pool parameter to empty for Snapshot-backed volumes
  e2e/cephfs.go
  internal/cephfs/store/volumeoptions.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#218 Syncing latest changes from upstream devel for ceph-csi
  .github/workflows/snyk-container-image.yaml
  internal/csi-common/server.go
Labels: approved, lgtm

#219 Syncing latest changes from upstream devel for ceph-csi
  internal/csi-addons/server/server.go
  internal/csi-common/server.go
  internal/csi-common/utils.go
Labels: approved, lgtm

#220 Syncing latest changes from upstream devel for ceph-csi
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
Labels: approved, lgtm

#222 [DOWNSTREAM-ONLY] add Praveen M to the team
  OWNERS_ALIASES
Labels: approved, lgtm

#224 Syncing latest changes from upstream devel for ceph-csi
  PendingReleaseNotes.md
  README.md
  api/deploy/kubernetes/cephfs/csi-config-map.go
  api/deploy/kubernetes/cephfs/csi-config-map.yaml
  api/deploy/kubernetes/cephfs/csidriver.yaml
  api/deploy/kubernetes/csi-config-map.go
  api/deploy/kubernetes/nfs/csi-config-map.go
  api/deploy/kubernetes/nfs/csi-config-map.yaml
  api/deploy/kubernetes/nfs/csidriver.yaml
  api/deploy/kubernetes/rbd/csi-config-map.go
  api/deploy/kubernetes/rbd/csi-config-map.yaml
  api/deploy/kubernetes/rbd/csidriver.yaml
  charts/ceph-csi-cephfs/templates/extra-deploy.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/templates/extra-deploy.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  internal/cephfs/core/volume.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/cephfs/csi-config-map.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/cephfs/csi-config-map.yaml
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/cephfs/csidriver.yaml
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/csi-config-map.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/doc.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/nfs/csi-config-map.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/nfs/csi-config-map.yaml
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/nfs/csidriver.yaml
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/rbd/csi-config-map.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/rbd/csi-config-map.yaml
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/rbd/csidriver.yaml
  vendor/modules.txt
Labels: approved, lgtm

#225 Syncing latest changes from upstream devel for ceph-csi
  build.env
  internal/cephfs/controllerserver.go
Labels: approved, lgtm

#226 Syncing latest changes from upstream devel for ceph-csi
  README.md
  actions/retest/go.mod
  actions/retest/go.sum
  actions/retest/vendor/modules.txt
  docs/ceph-csi-upgrade.md
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/signer/v4/middleware.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm
