Repository red-hat-storage/ceph-csi, pull requests merged in 2023-07, with the labels that each got.

#166 nfs: add support for `clients` in the StorageClass
  e2e/nfs.go
  e2e/utils.go
  examples/nfs/storageclass.yaml
  internal/nfs/controller/volume.go
Labels: approved, lgtm

#169 rbd: do not execute rbd sparsify when volume is in use
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm

#170 BUG 2225420: rbd: do not execute rbd sparsify when volume is in use
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/invalid-bug

#172 BUG 2225433: rbd: do not execute rbd sparsify when volume is in use
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/invalid-bug

#171 BUG 2225431: rbd: do not execute rbd sparsify when volume is in use
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/invalid-bug

#173 BUG 2225436: rbd: do not execute rbd sparsify when volume is in use
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/invalid-bug

#174 Revert "BUG 2225436: rbd: do not execute rbd sparsify when volume is in use"
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#177 Revert "BUG 2225431: rbd: do not execute rbd sparsify when volume is in use"
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/valid-bug

#176 Revert "BUG 2225420: rbd: do not execute rbd sparsify when volume is in use"
  internal/csi-addons/rbd/reclaimspace.go
  internal/rbd/diskusage.go
  internal/rbd/errors.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified
