Repository red-hat-storage/ceph-csi, pull requests merged in 2024-04, with the labels that each got.

#284 Syncing latest changes from upstream devel for ceph-csi
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
  internal/cephfs/groupcontrollerserver.go
Labels: approved, lgtm

#285 Syncing latest changes from upstream devel for ceph-csi
  .github/workflows/pull-request-commentor.yaml
  .mergify.yml
  README.md
  actions/retest/Dockerfile
  actions/retest/main.go
  docs/ceph-csi-upgrade.md
  e2e/deployment.go
  e2e/rbd.go
  internal/journal/voljournal.go
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/rbd_util.go
  internal/util/crypto.go
  internal/util/crypto_test.go
  internal/util/util.go
Labels: approved, lgtm

#287 Syncing latest changes from upstream devel for ceph-csi
  .mergify.yml
  build.env
Labels: approved, lgtm

#286 Syncing latest changes from devel for ceph-csi
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
  internal/cephfs/groupcontrollerserver.go
  internal/rbd/controllerserver.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/rbd/snapshot.go
Labels: approved, lgtm, bugzilla/valid-bug

#289 Syncing latest changes from upstream devel for ceph-csi
  internal/cephfs/controllerserver.go
  internal/rbd/controllerserver.go
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_util.go
  internal/util/topology.go
  internal/util/util.go
  scripts/k8s-storage/driver-cephfs.yaml
Labels: approved, lgtm

#292 Syncing latest changes from upstream devel for ceph-csi
  .mergify.yml
  build.env
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/config.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/gracefulswitch.go
  vendor/google.golang.org/grpc/internal/channelz/channel.go
  vendor/google.golang.org/grpc/internal/channelz/channelmap.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/id.go
  vendor/google.golang.org/grpc/internal/channelz/logging.go
  vendor/google.golang.org/grpc/internal/channelz/server.go
  vendor/google.golang.org/grpc/internal/channelz/socket.go
  vendor/google.golang.org/grpc/internal/channelz/subchannel.go
  vendor/google.golang.org/grpc/internal/channelz/syscall_linux.go
  vendor/google.golang.org/grpc/internal/channelz/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/channelz/trace.go
  vendor/google.golang.org/grpc/internal/channelz/types.go
  vendor/google.golang.org/grpc/internal/channelz/util_linux.go
  vendor/google.golang.org/grpc/internal/channelz/util_nonlinux.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/pretty/pretty.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/internal/xds_handshake_cluster.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, lgtm

#293 Syncing latest changes from upstream devel for ceph-csi
  internal/kms/azure_vault.go
Labels: approved, lgtm

#295 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/kms/api.go
  vendor/github.com/ceph/go-ceph/rbd/features.go
  vendor/github.com/ceph/go-ceph/rbd/features_nautilus.go
  vendor/github.com/ceph/go-ceph/rbd/rbd.go
  vendor/github.com/ceph/go-ceph/rbd/resize.go
  vendor/modules.txt
Labels: approved, lgtm

#296 Syncing latest changes from upstream devel for ceph-csi
  charts/ceph-csi-rbd/values.yaml
  deploy/csi-config-map-sample.yaml
  internal/rbd/rbd_util.go
  internal/util/csiconfig.go
  internal/util/csiconfig_test.go
  vendor/github.com/ceph/ceph-csi/api/deploy/kubernetes/csi-config-map.go
Labels: approved, lgtm

#297 Syncing latest changes from upstream devel for ceph-csi
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/pipe.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/testsync.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/modules.txt
  build.env
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/nfs/kubernetes/csi-nfsplugin-provisioner.yaml
  deploy/nfs/kubernetes/csi-nfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  e2e/rbd.go
  internal/rbd/rbd_util.go
  scripts/k8s-storage/driver-cephfs.yaml
Labels: approved, lgtm

#298 BUG 2264900: rbd: add ParentInTrash parameter in rbdImage struct
  e2e/rbd.go
  internal/rbd/rbd_util.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#300 Syncing latest changes from upstream devel for ceph-csi
  build.env
  e2e/cephfs.go
  e2e/errors_test.go
  e2e/nfs.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/utils.go
  go.mod
  internal/cephfs/groupcontrollerserver_test.go
  internal/cephfs/nodeserver_test.go
  internal/cephfs/store/volumeoptions_test.go
  internal/csi-addons/networkfence/fencing_test.go
  internal/csi-addons/rbd/replication_test.go
  internal/csi-common/utils_test.go
  internal/health-checker/filechecker_test.go
  internal/health-checker/statchecker_test.go
  internal/kms/kms_util_test.go
  internal/nfs/nodeserver/nodeserver_test.go
  internal/rbd/controllerserver_test.go
  internal/rbd/encryption_test.go
  internal/rbd/migration_test.go
  internal/rbd/nodeserver_test.go
  internal/rbd/rbd_attach.go
  internal/rbd/rbd_attach_test.go
  internal/rbd/rbd_util_test.go
  internal/util/cephcmds_test.go
  internal/util/cluster_mapping_test.go
  internal/util/credentials_test.go
  internal/util/crushlocation_test.go
  internal/util/csiconfig_test.go
  internal/util/k8s/parameters_test.go
  internal/util/read_affinity_test.go
  internal/util/reftracker/reftracker_test.go
  internal/util/util_test.go
Labels: approved, lgtm
