Repository red-hat-storage/ceph-csi, pull requests merged in 2024-09, with the labels that each got.

#354 BUG 2303177: util: exclude empty label values for crushlocation map
  internal/util/crushlocation.go
  internal/util/crushlocation_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#366 Syncing latest changes from upstream devel for ceph-csi
  charts/ceph-csi-cephfs/templates/csidriver-crd.yaml
  charts/ceph-csi-rbd/templates/csidriver-crd.yaml
  examples/cephfs/groupsnapshot.yaml
  examples/cephfs/groupsnapshotclass.yaml
  internal/rbd/nodeserver.go
Labels: approved, lgtm

#355 BUG 2303181: util: exclude empty label values for crushlocation map
  Makefile
  docs/metrics.md
  examples/rbd/storageclass.yaml
  internal/health-checker/checker.go
  internal/util/crushlocation.go
  internal/util/crushlocation_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#371 cephfs: Fix Removal of IPs from blocklist
  internal/csi-addons/cephfs/network_fence.go
  internal/csi-addons/networkfence/fencing.go
  internal/csi-addons/networkfence/fencing_test.go
Labels: approved, lgtm

#373 Bug 2308091: [release-4.17] cephfs: Fix Removal of IPs from blocklist
  docs/metrics.md
  examples/rbd/storageclass.yaml
  internal/csi-addons/cephfs/network_fence.go
  internal/csi-addons/networkfence/fencing.go
  internal/csi-addons/networkfence/fencing_test.go
  internal/health-checker/checker.go
  internal/util/crushlocation_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#374 Syncing latest changes from devel for ceph-csi
  internal/csi-addons/cephfs/network_fence.go
  internal/csi-addons/networkfence/fencing.go
  internal/csi-addons/networkfence/fencing_test.go
Labels: approved, lgtm

#375 Syncing latest changes from upstream devel for ceph-csi
  actions/retest/go.mod
  actions/retest/go.sum
  actions/retest/vendor/golang.org/x/oauth2/token.go
  actions/retest/vendor/modules.txt
  go.mod
  go.sum
  scripts/minikube.sh
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4/headers.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn/partitions.json
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/internal/endpoints/endpoints.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/golang.org/x/crypto/argon2/blamka_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.s
  vendor/golang.org/x/crypto/blake2b/blake2b_amd64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_amd64.s
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_hurd.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/term_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#377 Syncing latest changes from upstream devel for ceph-csi
  internal/rbd/replication.go
Labels: approved, lgtm

#378 BUG 2311885: rbd: fail DisableVolumeReplication() if image is not mirror disabled
  internal/rbd/replication.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#379 Syncing latest changes from devel for ceph-csi
  internal/rbd/replication.go
Labels: approved, lgtm

#380 Syncing latest changes from upstream devel for ceph-csi
  build.env
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/deployment.go
  e2e/nfs.go
  e2e/pvc.go
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/utils.go
  e2e/volumegroupsnapshot.go
  e2e/volumegroupsnapshot_base.go
  go.mod
  go.sum
  internal/rbd/rbd_util.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: approved, lgtm

#382 Syncing latest changes from devel for ceph-csi
  build.env
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/deployment.go
  e2e/nfs.go
  e2e/pvc.go
  e2e/rbd_helper.go
  e2e/snapshot.go
  e2e/utils.go
  e2e/volumegroupsnapshot.go
  e2e/volumegroupsnapshot_base.go
  go.mod
  go.sum
  internal/rbd/rbd_util.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/volumegroupsnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: approved, lgtm

#383 Syncing latest changes from upstream devel for ceph-csi
  README.md
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  internal/rbd/rbd_util.go
  vendor/modules.txt
Labels: approved, lgtm

#384 Syncing latest changes from devel for ceph-csi
  README.md
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  internal/rbd/rbd_util.go
  vendor/modules.txt
Labels: approved, lgtm

#385 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  vendor/github.com/cenkalti/backoff/v3/.gitignore
  vendor/github.com/cenkalti/backoff/v3/.travis.yml
  vendor/github.com/cenkalti/backoff/v3/LICENSE
  vendor/github.com/cenkalti/backoff/v3/README.md
  vendor/github.com/cenkalti/backoff/v3/backoff.go
  vendor/github.com/cenkalti/backoff/v3/context.go
  vendor/github.com/cenkalti/backoff/v3/exponential.go
  vendor/github.com/cenkalti/backoff/v3/retry.go
  vendor/github.com/cenkalti/backoff/v3/ticker.go
  vendor/github.com/cenkalti/backoff/v3/timer.go
  vendor/github.com/cenkalti/backoff/v3/tries.go
  vendor/github.com/hashicorp/vault/api/client.go
  vendor/github.com/hashicorp/vault/api/lifetime_watcher.go
  vendor/github.com/hashicorp/vault/api/request.go
  vendor/github.com/hashicorp/vault/api/response.go
  vendor/github.com/hashicorp/vault/api/secret.go
  vendor/github.com/hashicorp/vault/api/sudo_paths.go
  vendor/github.com/hashicorp/vault/api/sys_raft.go
  vendor/modules.txt
Labels: approved, lgtm

#386 Syncing latest changes from upstream devel for ceph-csi
  .github/workflows/auto-assign.yaml
  .github/workflows/build-multi-stage.yaml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/go-test.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/lint-extras.yaml
  .github/workflows/mergify-copy-labels.yaml
  .github/workflows/mod-check.yaml
  .github/workflows/publish-artifacts.yaml
  .github/workflows/pull-request-commentor.yaml
  .github/workflows/retest.yaml
  .github/workflows/snyk-container-image.yaml
  .github/workflows/snyk.yaml
  .github/workflows/stale.yaml
  .github/workflows/test-retest-action.yaml
  .github/workflows/tickgit.yaml
  PendingReleaseNotes.md
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/values.yaml
  cmd/cephcsi.go
  docs/deploy-cephfs.md
  docs/deploy-rbd.md
  go.mod
  go.sum
  internal/cephfs/driver.go
  internal/csi-addons/server/server.go
  internal/csi-common/server.go
  internal/csi-common/utils.go
  internal/nfs/driver/driver.go
  internal/rbd/driver/driver.go
  internal/util/util.go
  vendor/google.golang.org/grpc/experimental/stats/metricregistry.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/mem/buffer_slice.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm

#389 Syncing latest changes from upstream devel for ceph-csi
  README.md
  internal/controller/controller.go
  internal/csi-addons/rbd/volumegroup.go
  internal/rbd/group/util.go
  internal/rbd/group/volume_group.go
  internal/rbd/manager.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/rbd/types/manager.go
  internal/util/k8s/client.go
Labels: approved, lgtm

#391 Syncing latest changes from devel for ceph-csi
  README.md
  internal/controller/controller.go
  internal/csi-addons/rbd/volumegroup.go
  internal/rbd/group/util.go
  internal/rbd/group/volume_group.go
  internal/rbd/manager.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/rbd/types/manager.go
  internal/util/k8s/client.go
Labels: approved, lgtm
