Repository red-hat-storage/ceph-csi, pull requests merged in 2024-11, with the labels that each got.

#407 Syncing latest changes from devel for ceph-csi
  .github/workflows/build-multi-stage.yaml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/go-test.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/lint-extras.yaml
  .github/workflows/mod-check.yaml
  .github/workflows/publish-artifacts.yaml
  .github/workflows/retest.yaml
  .github/workflows/snyk-container-image.yaml
  .github/workflows/snyk.yaml
  .github/workflows/test-retest-action.yaml
  .github/workflows/tickgit.yaml
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/runtime/policy_bearer_token.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/response_error.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/policy/policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_bearer_token.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_http_trace.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_retry.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/MIGRATION.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/test-resources.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/challenge_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/ci.keyvault.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/constants.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/signer/v4/middleware.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/modules.txt
Labels: approved, lgtm

#410 Syncing latest changes from upstream devel for ceph-csi
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/volumegroupsnapshot.go
  e2e/volumegroupsnapshot_base.go
Labels: approved, lgtm

#411 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  internal/rbd/encryption.go
  internal/util/cephcmds.go
  internal/util/crypto.go
  internal/util/cryptsetup/cryptsetup.go
  internal/util/stripsecrets/stripsecrets.go
  vendor/github.com/google/pprof/profile/encode.go
  vendor/github.com/google/pprof/profile/merge.go
  vendor/github.com/google/pprof/profile/profile.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/formatter/formatter.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/internal/duration_bundle.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/internal/polling_signal_error.go
  vendor/github.com/onsi/gomega/matchers/have_field.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/ast/inspector/iter.go
  vendor/modules.txt
Labels: approved, lgtm

#413 Syncing latest changes from devel for ceph-csi
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  deploy/cephfs/kubernetes/cephfs.md
  deploy/rbd/kubernetes/rbd.md
  docs/cephfs/deploy.md
  docs/csi-addons/disaster-recovery.md
  docs/design/proposals/ceph-mount-corruption.md
  docs/design/proposals/cephfs-snapshot-backed-volumes.md
  docs/design/proposals/rbd-nbd.md
  docs/rbd/deploy.md
  e2e/pod.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/volumegroupsnapshot.go
  e2e/volumegroupsnapshot_base.go
  go.mod
  go.sum
  internal/rbd/encryption.go
  internal/util/cephcmds.go
  internal/util/crypto.go
  internal/util/cryptsetup/cryptsetup.go
  internal/util/stripsecrets/stripsecrets.go
  vendor/github.com/google/pprof/profile/encode.go
  vendor/github.com/google/pprof/profile/merge.go
  vendor/github.com/google/pprof/profile/profile.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/formatter/formatter.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/internal/duration_bundle.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/internal/polling_signal_error.go
  vendor/github.com/onsi/gomega/matchers/have_field.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/ast/inspector/iter.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm

#417 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  internal/rbd/controllerserver.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRole.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRoleWithSAML.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRoleWithWebIdentity.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRoot.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_GetFederationToken.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_GetSessionToken.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/deserializers.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/generated.json
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/serializers.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/types/errors.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/validators.go
  vendor/github.com/aws/smithy-go/CHANGELOG.md
  vendor/github.com/aws/smithy-go/encoding/httpbinding/path_replace.go
  vendor/github.com/aws/smithy-go/go_module_metadata.go
  vendor/modules.txt
Labels: approved, lgtm

#420 Syncing latest changes from devel for ceph-csi
  go.mod
  go.sum
  internal/rbd/controllerserver.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRole.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRoleWithSAML.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRoleWithWebIdentity.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_AssumeRoot.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_GetFederationToken.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/api_op_GetSessionToken.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/deserializers.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/generated.json
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/serializers.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/types/errors.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/validators.go
  vendor/github.com/aws/smithy-go/CHANGELOG.md
  vendor/github.com/aws/smithy-go/encoding/httpbinding/path_replace.go
  vendor/github.com/aws/smithy-go/go_module_metadata.go
  vendor/modules.txt
Labels: approved, lgtm

#421 Syncing latest changes from upstream devel for ceph-csi
  internal/cephfs/core/clone.go
  internal/cephfs/core/clone_test.go
  internal/cephfs/core/volume.go
  internal/cephfs/nodeserver.go
  internal/cephfs/store/fsjournal.go
  internal/rbd/nodeserver.go
  internal/util/idlocker.go
Labels: approved, lgtm

#425 DFBUGS-906: Prevent dataloss due to the concurrent RPC calls (occurrence is very low)
  internal/cephfs/nodeserver.go
  internal/rbd/nodeserver.go
  internal/util/idlocker.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#426 [release-4.18]: cephfs: log clone progress
  .github/workflows/snyk-container-image.yaml
  go.mod
  go.sum
  internal/cephfs/core/clone.go
  internal/cephfs/core/clone_test.go
  internal/cephfs/core/volume.go
  internal/cephfs/store/fsjournal.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug

#423 Syncing latest changes from upstream devel for ceph-csi
  .github/workflows/dependency-review.yaml
  .github/workflows/snyk-container-image.yaml
  api/go.mod
  api/go.sum
  api/vendor/github.com/stretchr/testify/assert/assertion_compare.go
  api/vendor/github.com/stretchr/testify/assert/assertion_format.go
  api/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  api/vendor/github.com/stretchr/testify/assert/assertion_order.go
  api/vendor/github.com/stretchr/testify/assert/assertions.go
  api/vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  api/vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  api/vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  api/vendor/github.com/stretchr/testify/require/require.go
  api/vendor/github.com/stretchr/testify/require/require.go.tmpl
  api/vendor/github.com/stretchr/testify/require/require_forward.go
  api/vendor/github.com/stretchr/testify/require/requirements.go
  api/vendor/modules.txt
  e2e/rbd.go
  e2e/rbd_helper.go
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/table_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/be_empty_matcher.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/contain_elements_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_each_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_exact_elements.go
  vendor/github.com/onsi/gomega/matchers/have_key_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_key_with_value_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_len_matcher.go
  vendor/github.com/onsi/gomega/matchers/internal/miter/type_support_iter.go
  vendor/github.com/onsi/gomega/matchers/internal/miter/type_support_noiter.go
  vendor/github.com/onsi/gomega/matchers/type_support.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
Labels: approved, lgtm

#427 Syncing latest changes from upstream devel for ceph-csi
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  go.sum
  internal/cephfs/controllerserver.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/server/storage/resource_encoding_config.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  vendor/modules.txt
Labels: approved, lgtm
