Repository red-hat-storage/ceph-csi, pull requests merged in 2025-08, with the labels that each got.

#588 Syncing latest changes from upstream devel for ceph-csi
  internal/csi-addons/rbd/replication.go
Labels: approved, lgtm

#592 [release-4.20] DFBUGS-3805: rbd: return replication status and status message in case of error
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-important, ci/skip/multi-arch-build

#595 DFBUGS-3740: FailedAttachVolume error when using restored PVC on app pod
  charts/ceph-csi-cephfs/README.md
  charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-cephfs/templates/provisioner-clusterrole.yaml
  charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml
  charts/ceph-csi-cephfs/templates/storageclass.yaml
  charts/ceph-csi-cephfs/values.yaml
  charts/ceph-csi-rbd/README.md
  charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml
  charts/ceph-csi-rbd/templates/provisioner-deployment.yaml
  charts/ceph-csi-rbd/templates/storageclass.yaml
  charts/ceph-csi-rbd/values.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
  deploy/cephfs/kubernetes/csi-cephfsplugin.yaml
  deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml
  deploy/rbd/kubernetes/csi-rbdplugin.yaml
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/deployment.go
  e2e/pod.go
  e2e/pvc.go
  e2e/rbd.go
  e2e/rbd_helper.go
  e2e/staticpvc.go
  e2e/utils.go
  examples/cephfs/storageclass.yaml
  examples/rbd/storageclass.yaml
  internal/cephfs/controllerserver.go
  internal/cephfs/core/metadata.go
  internal/cephfs/core/snapshot.go
  internal/cephfs/core/snapshot_metadata.go
  internal/cephfs/driver.go
  internal/cephfs/nodeserver.go
  internal/rbd/controllerserver.go
  internal/rbd/driver/driver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
  internal/util/util.go
  scripts/install-helm.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#599 [release-4.20]: Store userid in metadata
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/pod.go
  e2e/rbd.go
  internal/cephfs/controllerserver.go
  internal/cephfs/core/metadata.go
  internal/cephfs/driver.go
  internal/cephfs/nodeserver.go
  internal/rbd/controllerserver.go
  internal/rbd/driver/driver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
Labels: approved, lgtm, jira/valid-bug, ci/skip/multi-arch-build
