Repository red-hat-storage/ceph-csi, pull requests merged in 2025-06, with the labels that each got.

#538 [DOWNSTREAM-ONLY] Implement ListSnapshots RPC for CephFS and RBD
  internal/cephfs/controllerserver.go
  internal/cephfs/driver.go
  internal/rbd/controllerserver.go
  internal/rbd/driver/driver.go
  internal/rbd/snapshot.go
  internal/rbd/snapshot_test.go
Labels: approved, lgtm

#541 Syncing latest changes from upstream devel for ceph-csi
  .commitlintrc.yml
  PendingReleaseNotes.md
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  cmd/cephcsi.go
  docs/cephfs/deploy.md
  docs/rbd/deploy.md
  go.mod
  go.sum
  internal/cephfs/driver.go
  internal/csi-addons/rbd/volumegroup.go
  internal/csi-common/server.go
  internal/nfs/driver/driver.go
  internal/rbd/driver/driver.go
  internal/rbd/group_controllerserver.go
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/version.go
  vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/event/event.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_mapped.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/event_handler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/kind.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/warning_handler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/multi.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics/metrics.go
Labels: approved, lgtm

#543 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/internal/endpoints/endpoints.go
  vendor/github.com/hashicorp/hcl/decoder.go
  vendor/github.com/hashicorp/hcl/hcl/parser/parser.go
  vendor/github.com/hashicorp/hcl/parse.go
  vendor/github.com/hashicorp/vault/api/hcl_dup_attr_deprecation.go
  vendor/github.com/hashicorp/vault/api/logical.go
  vendor/github.com/hashicorp/vault/api/ssh_agent.go
  vendor/github.com/hashicorp/vault/api/sys_raft.go
  vendor/github.com/hashicorp/vault/api/sys_utilization_report.go
  vendor/github.com/pkg/xattr/xattr_solaris.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/trace/events.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: approved, lgtm

#545 Syncing latest changes from upstream devel for ceph-csi
  charts/ceph-csi-rbd/README.md
Labels: approved, lgtm

#549 [DOWNSTREAM-ONLY] add nikhil-ladha to the team
  OWNERS_ALIASES
Labels: approved, lgtm

#550 Syncing latest changes from devel for ceph-csi
  OWNERS_ALIASES
Labels: approved, lgtm

#551 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
  internal/nfs/controller/volume.go
  v3
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_developer_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/_metadata.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/tsp-location.yaml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/challenge_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/doc.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/fake_challenge.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/parse.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/signer/v4/stream.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn/partitions.json
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/ceph/go-ceph/cephfs/admin/subvolume_snapshot_path.go
  vendor/github.com/ceph/go-ceph/cephfs/file.go
  vendor/github.com/ceph/go-ceph/cephfs/permissions.go
  vendor/github.com/ceph/go-ceph/common/commands/interfaces.go
  vendor/github.com/ceph/go-ceph/internal/commands/commands.go
  vendor/github.com/ceph/go-ceph/internal/commands/trace.go
  vendor/github.com/ceph/go-ceph/rbd/encryption_load2.go
  vendor/github.com/ceph/go-ceph/rbd/rbd.go
  vendor/github.com/csi-addons/spec/lib/go/replication/replication.pb.go
  vendor/modules.txt
Labels: approved, lgtm

#552 Syncing latest changes from upstream devel for ceph-csi
  README.md
Labels: approved, lgtm

#556 [release-4.17] DFBUGS-2388: util: fix bug in health checker
  internal/health-checker/manager.go
  internal/health-checker/manager_test.go
  scripts/Dockerfile.test
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#558 Manual sync of d/s main to release-4.20 branch
  .github/workflows/pull-request-commentor.yaml
  .mergify.yml
  README.md
  go.mod
  go.sum
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
  internal/nfs/controller/volume.go
  v3
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_developer_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/_metadata.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/tsp-location.yaml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/challenge_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/doc.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/fake_challenge.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/parse.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/signer/v4/stream.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn/partitions.json
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/csi-addons/spec/lib/go/replication/replication.pb.go
  vendor/modules.txt
Labels: approved, lgtm, ci/skip/multi-arch-build

#559 [release-4.18] DFBUGS-1978: rebase: update golang.org/x/oauth2 to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
