Repository red-hat-storage/ceph-csi, pull requests merged in 2025-09, with the labels that each got.

#603 DFBUGS-3918: [release-4.20]: util: allow ParseClientIP to handle compressed ipv6 addresses
  internal/csi-addons/networkfence/fencing_test.go
  internal/util/util.go
  internal/util/util_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-important, ci/skip/multi-arch-build

#605 DFBUGS-3948: [release-4.20] rbd: volume demote after unpublish call
  internal/csi-addons/rbd/replication.go
  internal/csi-common/utils.go
  internal/csi-common/utils_test.go
  internal/rbd/controllerserver.go
  internal/rbd/nodeserver.go
  internal/rbd/rbd_util.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-important

#608 [release:420]: fix: cyclomatic complexity golangci-lint failure
  internal/csi-addons/rbd/replication.go
Labels: approved, lgtm, jira/valid-bug, ci/skip/multi-arch-build

#607 [DOWNSTREAM_ONLY] DFBUGS-3954: [release-4.20] rbd: add schedule again during group modification
  internal/csi-addons/rbd/volumegroup.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-important, ci/skip/multi-arch-build

#619 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/arm/internal/resource/resource_identifier.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_api_version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/poller.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_developer_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/developer_credential_util.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed-identity-matrix.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/local/server.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/authority/authority.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/resolvers.go
  vendor/modules.txt
Labels: approved, lgtm

#622 [DOWNSTREAM_ONLY] [release-4.20] ci: update custom tag for ceph cg support
  build.env
  scripts/Dockerfile.test
Labels: approved, lgtm, jira/valid-bug, ci/skip/multi-arch-build

#620 Syncing latest changes from upstream devel for ceph-csi
  .github/workflows/dependency-review.yaml
  .github/workflows/pull-request-commentor.yaml
  .mergify.yml
  go.mod
  go.sum
  internal/kms/aws_metadata.go
  internal/kms/aws_sts_metadata.go
  internal/kms/azure_vault.go
  internal/kms/keyprotect.go
  internal/kms/kmip.go
  internal/kms/secretskms.go
  internal/kms/vault_sa.go
  internal/kms/vault_tokens.go
  internal/nvmeof/controller/controllerserver.go
  internal/nvmeof/controller/controllerserver_test.go
  internal/rbd/rbd_healer.go
  vendor/github.com/aws/aws-sdk-go-v2/aws/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/configsources/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn/partitions.go
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn/partitions.json
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/modules.txt
Labels: approved, lgtm
