Repository red-hat-storage/ceph-csi, pull requests merged in 2025-04, with the labels that each got.

#510 Syncing latest changes from upstream devel for ceph-csi
  internal/rbd/driver/driver.go
  internal/rbd/group/volume_group.go
Labels: approved, lgtm

#511 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  internal/rbd/driver/driver.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/modules.txt
Labels: approved, lgtm

#504 [DOWNSTREAM-ONLY] rbd: add support for volume group mirroring
  build.env
  deploy/cephcsi/image/Dockerfile
  go.mod
  go.sum
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/volumegroup.go
  internal/rbd/controllerserver.go
  internal/rbd/errors/errors.go
  internal/rbd/group/group_mirror.go
  internal/rbd/group/util_test.go
  internal/rbd/group/volume_group.go
  internal/rbd/manager.go
  internal/rbd/mirror.go
  internal/rbd/types/group.go
  internal/rbd/types/manager.go
  scripts/Dockerfile.devel
  scripts/Dockerfile.test
  vendor/github.com/ceph/go-ceph/rbd/mirror_group.go
  vendor/modules.txt
Labels: approved, lgtm, ci/skip/multi-arch-build

#517 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, lgtm

#507 DFBUGS-1980: rebase: update go-jose to v4.0.5 to address CVE-2025-27144
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/shared.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#518 Syncing latest changes from upstream devel for ceph-csi
  internal/health-checker/manager.go
  internal/health-checker/manager_test.go
Labels: approved, lgtm

#523 [DOWNSTREAM-ONLY] add Shravani Vangur to the team
  OWNERS_ALIASES
Labels: approved, lgtm

#522 DFBUGS-2016: rebase: update golang.org/x/oauth2 to v0.27.0
  .github/workflows/build-multi-stage.yaml
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#520 DFBUGS-2091: util: fix bug in health checker
  internal/health-checker/manager.go
  internal/health-checker/manager_test.go
Labels: approved, jira/valid-bug, jira/valid-reference, jira/severity-moderate

#526 Syncing latest changes from upstream devel for ceph-csi
  e2e/cephfs.go
  e2e/cephfs_helper.go
  e2e/pvc.go
  e2e/utils.go
Labels: approved, lgtm

#527 [DOWNSTREAM-ONLY] [release-4.19] DFBUGS-2348: group: use groupsnapshotschedule api for group mirror
  deploy/cephcsi/image/Dockerfile
  go.mod
  go.sum
  internal/rbd/group/group_mirror.go
  scripts/Dockerfile.devel
  scripts/Dockerfile.test
  vendor/github.com/ceph/go-ceph/rbd/admin/admin.go
  vendor/github.com/ceph/go-ceph/rbd/admin/groupsschedule.go
  vendor/github.com/ceph/go-ceph/rbd/mirror_group.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#528 Syncing latest changes from upstream devel for ceph-csi
  docs/capabilities.md
Labels: approved, lgtm
