Repository red-hat-storage/ceph-csi, pull requests merged in 2025-02, with the labels that each got.

#464 DFBUGS-1159: Misuse of ServerConfig.PublicKeyCallback (CVE-2024-45337)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#466 DFBUGS-1215: Non-linear parsing of case-insensitive content (CVE-2024-45338)
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#470 Syncing latest changes from upstream devel for ceph-csi
  go.mod
  go.sum
  vendor/k8s.io/csi-translation-lib/plugins/portworx.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, lgtm

#472 DFBUGS-1613: CVE-2025-0426 cephcsi-container: node denial of service via kubelet checkpoint API
  deploy/cephcsi/image/Dockerfile
  go.mod
  go.sum
  scripts/Dockerfile.devel
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/server/storage/resource_encoding_config.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/debug/resource_usage_gatherer.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#474 Syncing latest changes from upstream devel for ceph-csi
  docs/rbd/deploy.md
  e2e/rbd.go
  e2e/rbd_helper.go
  examples/rbd/storageclass.yaml
  internal/csi-addons/rbd/encryptionkeyrotation.go
  internal/csi-addons/rbd/replication.go
  internal/csi-addons/rbd/replication_test.go
  internal/rbd/clone.go
  internal/rbd/controllerserver.go
  internal/rbd/errors.go
  internal/rbd/group/util.go
  internal/rbd/manager.go
  internal/rbd/qos.go
  internal/rbd/qos_test.go
  internal/rbd/rbd_journal.go
  internal/rbd/rbd_util.go
  internal/rbd/rbd_util_test.go
  internal/rbd/snapshot.go
  internal/util/errors.go
  internal/util/errors_test.go
Labels: approved, lgtm

#473 DFBUGS-1614: CVE-2025-0426 cephcsi-container: node denial of service via kubelet checkpoint API
  deploy/cephcsi/image/Dockerfile
  go.mod
  go.sum
  scripts/Dockerfile.devel
  vendor/go.opentelemetry.io/otel/metric/noop/noop.go
  vendor/k8s.io/api/admissionregistration/v1/types.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/options/tracing.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_unsupported.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/debug/resource_usage_gatherer.go
  vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
  vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
  vendor/k8s.io/kubernetes/test/utils/density_utils.go
  vendor/k8s.io/kubernetes/test/utils/deployment.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/kubernetes/test/utils/runners.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#475 Syncing latest changes from upstream devel for ceph-csi
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  go.sum
  internal/rbd/rbd_journal.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/MIGRATION.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/responses.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/time_unix.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/tsp-location.yaml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/challenge_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/ci.keyvault.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/constants.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/confidential/confidential.go
  vendor/github.com/ceph/go-ceph/internal/retry/sizer.go
  vendor/github.com/ceph/go-ceph/rbd/encryption.go
  vendor/github.com/ceph/go-ceph/rbd/encryption_load2.go
  vendor/github.com/ceph/go-ceph/rbd/encryption_opt_luks.go
  vendor/github.com/ceph/go-ceph/rbd/group_snap.go
  vendor/github.com/ceph/go-ceph/rbd/group_snap_info.go
  vendor/github.com/ceph/go-ceph/rbd/mirror.go
  vendor/github.com/ceph/go-ceph/rbd/sparsify.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
Labels: approved, lgtm

#481 [DOWNSTREAM-ONLY] add Niraj Yadav to the team
  OWNERS_ALIASES
Labels: approved, lgtm

#484 DFBUGS-1214: [release-4.16] Non-linear parsing of case-insensitive content (CVE-2024-45338)
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#485 DFBUGS-1658: [release-4.17] Non-linear parsing of case-insensitive content (CVE-2024-45338)
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#482 DFBUGS-1210: [release-4.14] Non-linear parsing of case-insensitive content (CVE-2024-45338)
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#483 DFBUGS-1211: [release-4.15] Non-linear parsing of case-insensitive content (CVE-2024-45338)
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#486 Syncing latest changes from upstream devel for ceph-csi
  internal/rbd/controllerserver.go
  internal/rbd/controllerserver_test.go
  internal/rbd/snapshot.go
  internal/rbd/snapshot_test.go
Labels: approved, lgtm

#488 Syncing latest changes from upstream devel for ceph-csi
  internal/rbd/controllerserver.go
Labels: approved, lgtm

#487 DFBUGS-1669: rbd: fix bug in rbdVol.Exists() in PVC-PVC clone case
  internal/rbd/rbd_journal.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#429 DFBUGS-1011: Prevent dataloss due to the concurrent RPC calls (occurrence is very low)
  docs/metrics.md
  examples/rbd/storageclass.yaml
  internal/cephfs/nodeserver.go
  internal/cephfs/store/volumeoptions.go
  internal/health-checker/checker.go
  internal/rbd/nodeserver.go
  internal/util/crushlocation_test.go
  internal/util/idlocker.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#433 DFBUGS-913: Prevent dataloss due to the concurrent RPC calls (occurrence is very low)
  internal/cephfs/nodeserver.go
  internal/rbd/nodeserver.go
  internal/util/idlocker.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#424 DFBUGS-910: Prevent dataloss due to the concurrent RPC calls (occurrence is very low)
  internal/cephfs/nodeserver.go
  internal/rbd/nodeserver.go
  internal/util/idlocker.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical

#435 DFBUGS-914: Prevent dataloss due to the concurrent RPC calls (occurrence is very low)
  internal/cephfs/nodeserver.go
  internal/rbd/nodeserver.go
  internal/util/idlocker.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, jira/severity-critical
